/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketing;

import javax.swing.JOptionPane;
import koneksi.Koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author ASUS
 */
public class FormTiket extends javax.swing.JFrame {

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        loadWisata();
    loadPengunjung();
    tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbWisata = new javax.swing.JComboBox<>();
        cbPengunjung = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiket = new javax.swing.JTable();
        txtTanggal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbWisata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWisataActionPerformed(evt);
            }
        });

        cbPengunjung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPengunjungActionPerformed(evt);
            }
        });

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Wisata", "Pengunjung", "Jumlah", "Total", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblTiket);

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        jLabel2.setText("Jumlah");

        jLabel3.setText("Tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(cbPengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void cbWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWisataActionPerformed
       
    }//GEN-LAST:event_cbWisataActionPerformed

    private void cbPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPengunjungActionPerformed
        
    }//GEN-LAST:event_cbPengunjungActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
 try {
        int idWisata = Integer.parseInt(cbWisata.getSelectedItem().toString().split(" - ")[0]);
        int idPengunjung = Integer.parseInt(cbPengunjung.getSelectedItem().toString().split(" - ")[0]);

        String sql = "INSERT INTO tiket VALUES (NULL, ?, ?, ?, ?, ?)";
        Connection con = Koneksi.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setInt(1, idWisata);
        pst.setInt(2, idPengunjung);
        pst.setInt(3, Integer.parseInt(txtJumlah.getText()));
        pst.setInt(4, Integer.parseInt(txtTotal.getText()));
        pst.setDate(5, java.sql.Date.valueOf(txtTanggal.getText()));

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan");
        tampilData();
        kosongkan();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased
        hitungTotal();
    }//GEN-LAST:event_txtJumlahKeyReleased

    /**
     * @param args the command line arguments
     */
    
    void hitungTotal() {
    try {
        String wisata = cbWisata.getSelectedItem().toString();
        int idWisata = Integer.parseInt(wisata.split(" - ")[0]);

        String sql = "SELECT harga_tiket FROM wisata WHERE id_wisata=?";
        Connection con = Koneksi.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, idWisata);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int harga = rs.getInt("harga_tiket");
            int jumlah = Integer.parseInt(txtJumlah.getText());
            txtTotal.setText(String.valueOf(harga * jumlah));
        }
    } catch (Exception e) {
        // biarkan kosong saat belum valid
    }
}
void tampilData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Wisata");
    model.addColumn("Pengunjung");
    model.addColumn("Jumlah");
    model.addColumn("Total");
    model.addColumn("Tanggal");
     
    try {
        String sql = "SELECT t.id_tiket, w.nama_wisata, p.nama_pengunjung, "
           + "t.jumlah_tiket, t.total_harga, t.tanggal "
           + "FROM tiket t "
           + "JOIN wisata w ON t.id_wisata = w.id_wisata "
           + "JOIN pengunjung p ON t.id_pengunjung = p.id_pengunjung";
        
        Connection con = Koneksi.getConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt(1),
                rs.getString(2),
                rs.getString(3),
                rs.getInt(4),
                rs.getInt(5),
                rs.getDate(6)
            });
        }
        tblTiket.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
   void loadWisata() {
    try {
        String sql = "SELECT * FROM wisata";
        Connection con = Koneksi.getConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        cbWisata.removeAllItems();
        while (rs.next()) {
            cbWisata.addItem(rs.getInt("id_wisata") + " - " + rs.getString("nama_wisata"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
void loadPengunjung() {
    try {
        String sql = "SELECT * FROM pengunjung";
        Connection con = Koneksi.getConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        cbPengunjung.removeAllItems();
        while (rs.next()) {
            cbPengunjung.addItem(rs.getInt("id_pengunjung") + " - " + rs.getString("nama_pengunjung"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
void kosongkan() {
    txtJumlah.setText("");
    txtTotal.setText("");
    txtTanggal.setText("");
}
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbPengunjung;
    private javax.swing.JComboBox<String> cbWisata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTiket;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
