/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketing;

/**
 *
 * @author ASUS
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuWisata = new javax.swing.JMenuItem();
        menuPengunjung = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuTiketmenuTiket = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgrond.jpg"))); // NOI18N

        menuMaster.setText("Master Data");

        menuWisata.setText("Data Wisata");
        menuWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWisataActionPerformed(evt);
            }
        });
        menuMaster.add(menuWisata);

        menuPengunjung.setText("Data Pengunjung");
        menuPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengunjungActionPerformed(evt);
            }
        });
        menuMaster.add(menuPengunjung);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        menuTiketmenuTiket.setText("Pemesanan Tiket");
        menuTiketmenuTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTiketmenuTiketActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuTiketmenuTiket);

        jMenuBar1.add(menuTransaksi);

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWisataActionPerformed
        new FormWisata().setVisible(true);
    }//GEN-LAST:event_menuWisataActionPerformed

    private void menuPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengunjungActionPerformed
        new FormPengunjung().setVisible(true);
    }//GEN-LAST:event_menuPengunjungActionPerformed

    private void menuTiketmenuTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTiketmenuTiketActionPerformed
        new FormTiket().setVisible(true);
    }//GEN-LAST:event_menuTiketmenuTiketActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        new MenuUtama().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPengunjung;
    private javax.swing.JMenuItem menuTiketmenuTiket;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem menuWisata;
    // End of variables declaration//GEN-END:variables
}
